//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebXemPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int FilmID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Des { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public int CommentID { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual User User { get; set; }
    }
}
