//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebXemPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int UserID { get; set; }
        public int VoucherID { get; set; }
        public Nullable<double> Money { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public int HistoryID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
